name: Flake8

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install flake8-html

    - name: Run Flake8
      id: flake8
      run: |
        mkdir -p reports
        flake8 . --format=html --htmldir=reports/flake8_report || echo "Flake8 failed"

    - name: Convert HTML report to PNG
      if: ${{ failure() }}
      run: |
        apt-get update && apt-get install -y wkhtmltopdf
        wkhtmltoimage --format png reports/flake8_report/index.html static_analysis_reports/png/flake8_report.png

    - name: Create Static Analysis Reports Folder
      run: |
        mkdir -p static_analysis_reports/html
        mkdir -p static_analysis_reports/png

    - name: Copy Flake8 HTML reports to repository
      run: |
        cp -r reports/flake8_report/* static_analysis_reports/html/
        echo "Flake8 HTML reports copied to static_analysis_reports/html folder"

    - name: Copy Flake8 PNG reports to repository
      if: ${{ failure() }}
      run: |
        cp -r reports/flake8_report/* static_analysis_reports/png/
        echo "Flake8 PNG reports copied to static_analysis_reports/png folder"

    - name: Commit Reports to Repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@users.noreply.github.com"
        git add static_analysis_reports
        git commit -m "Add Flake8 reports"
        git push
